blank_issues_enabled: false
contact_links:
  - name: pyHIBP Issue Tracker
    url: https://gitlab.com/kitsunix/pyHIBP/pyHIBP/-/issues
    about: |
      Please report any issues on the GitLab.com issue tracker.
      You may use your GitHub account to log into GitLab.com,
      if desired.
